### ISSUE TITLE
No new content since a month

### ISSUE THREAD

**Issue by brisacier** [petosorus/ckanlalan#2]
Ever since this past month, there has been no new content on the website.

How to reproduce :
1) go to : http://www.ckanlalan.fun/
2) notice the lack of new content
3) get angry

**Comment by guillaume-girard** [comment]
Thank you brisacier for this good first issue.

I totally reproduce the 3 steps you described on my computer.

Will be fixed asap in confcall

**Comment by RoyDePoy** [comment]
@guillaume-girard I sent you some ideas on discord, are you free tomorrow?

**Comment by guillaume-girard** [comment]
Fixed in commit 6df696379fca7b177579809ba21e0ac508a1be97

**Comment by guillaume-girard** [comment]
@brisacier ok
