### ISSUE TITLE
Multiple clicks start multiple songs

### ISSUE THREAD

**Issue by brisacier** [petosorus/ckanlalan#4]
--------------------
💀 **NEW ISSUE** 💀 
--------------------
📜 **TLDR** : multiple clicks on the page starts new instances of the song (not stonks 📉 )

------------------------------
💻 **HOW TO REPRODUCE** 💻 
------------------------------
👉 First click on site :
✔️  music starts as expected

👉 Any further clicks :
❌ starts another song, overlapping the previous one (😨😨😨😨)

Can be a feature to mimick "les quatre quatre saisons" but overall it's not a desired behavior from the site.

_💯 ~ This issue was brought to you by the emoji squad ~ 💯_

**Comment by yTroude** [comment]
I use feature to add more "quadrille des gilets-jaunes" to my "menuet des villains". changing this break my workflow plz if fix add option to kepp current behavour thxs

**Comment by RoyDePoy** [comment]
>Can be a feature to mimick "les quatre quatre saisons"

Indeed this is a feature. 

>changing this break my workflo 

Tough luck
